name: sample_action

on: workflow_dispatch

jobs:
    echo_hello:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "Hello actions"
    
    python_hello:
        runs-on: ubuntu-22.04
        needs:
            - echo_hello
        steps:
            - run: print("Hello actions from python")
              shell: python
        
